### ISSUE TITLE
README should have more useful info

### ISSUE THREAD

**Issue by ebenenglish** [marriott-library/newspaper_works#10]
**Descriptive Summary**
Add more information to the main README for the gem

**Rationale**
Including info about modeling, project context, and installation details makes the code more likely to be used.

**Expected outcomes**
A detailed, well-organized, and user-friendly README.

In some cases, it may be preferable to use Github wiki pages for more in-depth examples/instructions. Links to the those pages should be provided in the README.

Possible things to add:
* ☑ table of contents?
* ☑ explanation of the purpose of the gem
* ☑ link to PCDM profile
* ~~relationship to `NewspaperViews` gem~~
* ☑ grant funding credit (potentially w/IMLS logo)
* ☑ institutional credits (BPL/UU)
* ☑ requirements/prerequisites
* ☑basic install steps
* _(partially done)_ customizations necessary in local app (not handled by install generator)
  - ☑ Geonames username
  - ☑ Configure `config/initializers/hyrax.rb` to make uploads optional.
  - ~~(optionally) remove deposit agreement checkbox~~.
* ☑ dev/testing setup
* links to wiki pages with detailed usage notes (console, batch uploads, etc.)
* ☑ build status (link to Travis-CI image, once #13 is resolved)?
```
[![Build Status](https://travis-ci.org/marriott-library/newspaper_works.svg?branch=master)](https://travis-ci.org/marriott-library/newspaper_works)
  ```

This is a starter list, further suggestions welcome!

**Comment by seanupton** [comment]
Updated description to remind me to add build-status image to the README once we have builds on Travis-CI working.

**Comment by seanupton** [comment]
Much of this work was accomplished in the scope of #47.  We need a review of this ticket's description to see if there is any remaining scope that we care about re: minor edits to README.  I suspect that we want to mention Hyrax settings for add/edit forms — make deposit agreement not required to save, make upload non-required by default (the latter is especially important, as we have work types that have no files themselves).
