### ISSUE TITLE
NDNP issue and page enumertion, metadata

### ISSUE THREAD

**Issue by seanupton** [marriott-library/newspaper_works#105]
## Goals

As part of #80, provide components to traverse a single issue's data in an NDNP data directory, given a path to the issue XML.  Represent the data in the XML and binary files as a simple, easily traversed object model for use by higher-level traversal (integration) components.

## Deliverables

Create components necessary to:

* Construct a `NewspaperWorks::Ingest::NDNP::IssueIngest` object, given a path
  to issue XML, which should:
  - mixin `Enumerable`
    - Enumerates pages, in the order of the "Page Sequence Number" field,
      as described in
      "Appendix A: Digital Asset Metadata Elements - Dictionary"
      of _NDNP Technical Guidelines_ (this is `mods:start`, not `mods:number`)
  - Provide each the following methods:
    - `.metadata` — returns a `NewspaperWorks::Ingest::NDNP::IssueMetadata` object
    - `.identifier` — as proxy to `.metadata.identifier`, identifier for issue
    - `.each` — integration point for Enumerable, as described above, where
      `NewspaperWorks::Ingest::NDNP::PageIngest` objects, described below,
      for each page are constructed upon iteration.
    - `.size` — number of pages contained
    - `.path` — path to issue XML
* Construct a `NewspaperWorks::Ingest::NDNP::IssueMetadata` object, which:
  - May be constructed with either a path to issue xml, or with a reference
    to an IssueIngest object which has a `.path` method.
  - Has methods for all descriptive metadata fields for a newspaper issue:
    - as described in wiki [here](https://github.com/marriott-library/newspaper_works/wiki/NDNP-XML-to-NewspaperWorks-metadata-profile-mapping#newspaperissue)
    - named and accessed the same as `NewspaperIssue` model properties,
    - in a data format for each field matching the type/format requirements
      of the fields within `NewspaperIssue`.
* Construct a `NewspaperWorks::Ingest::NDNP::PageIngest` object, which:
  - given, upon construction:
    - an `IssueIngest` (parent) object, AND
    - a sequence number (integer) locally, uniquely identifying the page
      within its parent issue.
  - will provide methods for the following:
    - `.issue` — returns parent issue
    - `.identifier` — shall be a String composing the identifier of the issue
      and the sequence number.
    - `.metadata` — returns a `NewspaperWorks::Ingest::NDNP::PageMetadata` object
  - and shall also behave like a hash/mapping of destination names to files:
    - where (String) keys ("destination name") are either:
      - "primary" (primary file asset), OR
      - a file extension (e.g. `'jp2'`)
    - values are paths to files
    - _to be provided via method_missing proxy implementation or equivalent_.
* Construct a `NewspaperWorks::Ingest::NDNP::PageMetadata` object, that:
  - Provides methods for each field described in the wiki, [here](https://github.com/marriott-library/newspaper_works/wiki/NDNP-XML-to-NewspaperWorks-metadata-profile-mapping#newspaperpage)
  - And provides the following additional methods not described in the wiki:
    - `.page_number` — human-readable page number (String).
    - `.sequence_number` — integer value for page
* Construct RSpec tests for all of the above four classes.

## Integration story:

These components shall be used by other higher-level components of an NDNP ingest to traverse the issue/page data and access files and metadata.

**Comment by ebenenglish** [comment]
Closed via #112.
