### ISSUE TITLE
NDNP BatchIngester class, orchestrates programmatic ingest

### ISSUE THREAD

**Issue by seanupton** [marriott-library/newspaper_works#115]
The primary vehicle for NDNP Ingest (user story #80) must be a set of classes that can be invoked programmatically to, given a local path to an NDNP batch, ingest the entirety of the content of that batch.  Such components should do the "heavy lifting" of import/ingest on behalf of:

(1) Ad-hoc ingests using rails console
(2) Command-line tools (see #118)
(3) Future ingest web UI or remote API (outside of scope of #80 user story).

## Implementation

* Create a `NewspaperWorks::Ingest::NDNP::BatchIngester` class:
  - constructed with a `path` argument, where path points to batch XML or containing directory;
  - an `.ingest` method to import all content from said batch, which shall iterate over all issues enumerated by `NewspaperWorks::Ingest::NDNP::BatchXMLIngest` data (implemented in #116).
* Create finer-grained classes to facilitate creation of issues, pages, containers on behalf of BatchIngester class, such that:
  - A publication is found or created: search using ActiveFedora finder methods for a `NewspaperTitle` work for respective publication LCCN, or create a new NewspaperTitle work for each respective LCCN encountered, if one does not already exist.  Newly created publications should have as much metadata set, and shall be the "parent" of imported issues.
  - NewspaperIssues are created, and 

### Expected classes and responsibility:
* `NewspaperWorks::Ingest::NDNP::BatchIngester`
  - uses `NewspaperWorks::Ingest::NDNP::BatchIngest` as source enumerable.
* `NewspaperWorks::Ingest::NDNP::IssueIngester`
  - uses `NewspaperWorks::Ingest::NDNP::IssueIngest` as source data
     - As enumerable of pages.
     - As a means to access metadata values for issue via `NewspaperWorks::Ingest::NDNP::IssueMetadata`
  - Responsible for creating `NewspaperIssue` asset and setting its metadata.
  - Also responsible for finding or creating publication (`NewspaperTitle`) associated with issue, and setting basic metadata on created publication.
* `NewspaperWorks::Ingest::NDNP::PageIngester`
  - used by IssueIngester above to ingest pages
  - uses `NewspaperWorks::Ingest::NDNP::PageIngest` as source data
     - As enumerable of page files via `.files` accessor/attribute.
     - As a means to access metadata values for issue via `NewspaperWorks::Ingest::NDNP::PageMetadata`
  - Responsible for creating `NewspaperPage` asset,
     - Setting its metadata, and
     - Ingesting all files and derivatives via `NewspaperWorks::Data::WorkFiles` attachment adapter(s).
  - Responsible for being entry point of ensuring that any reel associated with page exists, via...
* `NewspaperWorks::Ingest::NDNP::ContainerIngester`
  - instantiated by PageIngester above to ensure existence of reel asset (NewspaperContainer).
  - Find-or-create container by its reel number, stored using a value inside `.identifier` (array).
  - uses `NewspaperWorks::Ingest::NDNP::ContainerIngest` as source data
     - As a means to access metadata values for reel via `NewspaperWorks::Ingest::NDNP::ContainerMetadata`
  - When NewspaperContainer is created, it is associated with NewspaperTitle (transitive relation via page via issue).
  - A `.link` method given a `page` argument (NewspaperPage asset object) shall link the page to the container asset for the reel.

#### Use of source data

_Source data is provided by a variety of classes that front for NDNP XML data, as implemented in issues #116, #105._

* Issue, page, container metadata shall conform to the mappings described in the [wiki](https://github.com/marriott-library/newspaper_works/wiki/NDNP-XML-to-NewspaperWorks-metadata-profile-mapping)

#### NewspaperTitle (publication) assets
* If a publication asset does not exist as a NewspaperTitle object, it shall be created;
  - upon creation, metadata for title and possibly place of publication shall be copied.
  - lccn should be set as a value in the NewspaperTitle.lccn property.
* If a publication does already exist for LCCN, it should be created.
* If a place name exists in parentheses of the title label for the publication;
  - The system should attempt to look up place of publication URI for the asset by using Geonames API.
  - The place name should be removed from the final title set on the NewspaperTitle asset.

#### NewspaperIssue assets
* NewspaperIssue is created for each issue, metadata copied, and all constituent pages imported and linked.

#### NewspaperPage assets
* NewspaperPage assets created for each page, for each issue
* Fileset created for primary file
* Metadata imported
* Primary TIFF file attached
* Derivative ALTO, JPG, JP2, PDF files attached.

#### NewspaperContainer assets
* When reel data is available, every page with an associated reel shall have such reel found or created, then linked.  When created, metadata should be copied per mapping in wiki.
* Creation/find of container (and linking to publication) shall be a distinct phase from...
* ...a `.link` method on the `ContainerIngester` class to link the page to the container.

#### General operation notes: 
* Enumeration and performance of batch work is serial, not concurrent; we may later refactor for concurrency and more async work, but that is not in the scope of this issue.
* Aspects of file attachment are asynchronous, via the use of the WorkFiles adapter (and by consequence, the actor stack and multiple Hyrax and NewspaperWorks jobs re: derivatives).
  - For example, creation of other text (JSON, plain) derivatives from ALTO happens here (see #107).
* A practical production ingest should use a job runner with retries (e.g. Sidekiq, or similar) for any incidental async jobs, which may run on a distinct node from the work creation aspects of ingest provided here.
* Ingest makes practical attempt to deal with the following:
  - Older format (?) alternative for access to publication held_by and title metadata, as seen in one of our samples (the xpath is different from mapping in wiki).
  - Missing reel data (no container created).

**Comment by ebenenglish** [comment]
Closed via #139.
