### ISSUE TITLE
Command-line wrapper for NDNP BatchIngester

### ISSUE THREAD

**Issue by seanupton** [marriott-library/newspaper_works#118]
Command-line wrapper for NDNPBatchIngester (ref: #115), which takes one or more arguments point to a batch ~~one or more batches~~.

## Expected deliverables

* Rake task `newspaper_works:ndnp_ingest` with `--path` argument.
* Means to execute, deal with option parsing of the above task, in an alternate constructor of `NewspaperWorks::Ingest::NDNP::BatchIngester` class.
* Tests for rake task (outcome) and for individual implementation details implemented in the `BatchIngester` class.

## Out of scope

* Multiple batch support, due to limitations in rake argument handling.

**Comment by ebenenglish** [comment]
Closed via #150
