### ISSUE TITLE
Fileset permissions do not match ingested page via NewspaperPageIngest

### ISSUE THREAD

**Issue by seanupton** [marriott-library/newspaper_works#125]
Related to #38, when a `NewspaperPage` work object is created by `NewspaperWorks::Ingest::NewspaperPageIngest` (whether as part of an issue ingest, or as a single page ingest), we must ensure that the contained fileset permissions and visibility match the parent (page) work.

Not having this match of permissions and visibility risks **breaking IIIF viewing**.

## Expecations:
When ingesting a page, either individually, or as part of PDF ingest;
This page should have a contained fileset with the primary file attached;
And the permissions and visibility of the fileset, on creation of that fileset, should match the permissions and visibility of the NewspaperPage object containing the fileset.

## Notes:
We need to do this outside of the actor stack (in callback) because the Hyrax CreateWithRemoteFilesActor unfortunately has inconsistent behavior vs the Hyrax upload process implementation with regard to invoking the InheritPermissionsJob shipped in Hyrax.  Since most ingest processes I have heard about from community at large, and our implementation all use CreateWithRemoteFilesActor for attachment, we need a way to copy these permissions as soon as the fileset is created.

**Comment by ebenenglish** [comment]
Fixed via #127.
