### ISSUE TITLE
Rakefile tweaks for testing

### ISSUE THREAD

**Issue by seanupton** [marriott-library/newspaper_works#13]
We need some modifications to the Rakefile regarding running specs and Travis-CI...

1. Make default task :ci
2. Remove duplicate RakeTask.new, or at least verify that running `rake spec` does not run specs twice.
3. Create a rake task [https://github.com/samvera/hyrax/blob/master/tasks/hyrax_dev.rake#L14-L19](similar to Hyrax) that loads wrappers before invoking specs.
4. Make :ci task invoke the above task in step 3.

**Comment by brianmcbride** [comment]
This issue was resolved with PR https://github.com/marriott-library/newspaper_works/pull/16
