### ISSUE TITLE
PDF ingest, edit of issue work duplicates child pages

### ISSUE THREAD

**Issue by seanupton** [marriott-library/newspaper_works#140]
Adjust the NewspaperWorksUploadActor and/or any jobs or components it is using to avoid duplicating creation of child pages upon Edit of work.

## Duplicating:

1. Upload multi-page PDF to newly created newspaper issue.
2. Edit the metadata or permissions of this issue.
3. Wait for jobs to run (using sidekiq), then you will see duplicative pages below already imported pages:

![screenshot of duplicate page child assets](https://snag.gy/gnIP7R.jpg)

## Approaching the problem

* If there are no uploads in the edit, we should avoid creating child pages.
  - However, if necessary, compare existing stored PDF checksum to any upload to avoid triggering page creation when pages already exist.
  - Edit *should* create pages on update if and only if (any) pages are missing, and only those missing pages (indexed by sequence).

**Comment by ebenenglish** [comment]
Fixed via #177
