### ISSUE TITLE
create issue-level PDF object from page-level batch ingest

### ISSUE THREAD

**Issue by ebenenglish** [marriott-library/newspaper_works#155]
**Background**
In the [Ingest Scenarios](https://drive.google.com/open?id=10KnzsHubEeRRVH1K8CoCVzq5295ONzq94VHDUMzAskg) document, we indicated that an NDNP ingest would create NewspaperIssue objects, and compile child Page object files into a set of Issue-level files that would be attached as FileSets.

The compiled PDF is the most essential of these objects, and should take highest priority. (We will create separate issues for the other file types (text, METS XML manifest) later.)

The text should also be indexed as searchable full text, matching the current PDF ingest functionality.

**Rationale**
Without an Issue-level PDF file, getting Hyrax to render the IIIF viewer on the Issue show page looks like it will take a lot of work. There are several issues related to why the viewer will not currently render for NDNP-batch created Issues:
1. The `presenter.representative_id.present?` checks in `app/views/hyrax/base/representative_media` fail
2. The IIIF manifest (as rendered by default) returns `"@type":"sc:Collection"` rather than `"@type":"sc:Manifest"`
    * (I have not delved into why this is happening.)

An issue-level PDF is also likely to appeal to users, and is a feature offered by several newspaper systems (Example: [Michigan Daily](https://digital.bentley.umich.edu/midaily/mdp.39015071754738/723)).

**Expected Behavior**
As an admin user
When I run a batch ingest of page level files
And I view the results of the ingest in the UI
I should be able to view a page for each Issue in the batch
And the page should show the IIIF viewer with the full issue
And the text should be searchable
And I should be able to download the issue as a PDF

**This ticket will be complete when**
Functionality and user story described above is implemented and tested.

**Comment by seanupton** [comment]
Dropping this link here as a bookmark/reminder, may or may not be relevant to how we approach generating the PDF with Ghostscript: 

https://www.linux.com/news/putting-together-pdf-files

I just used this to create a minimal multi-page test fixture PDF I plan to use on another issue, but I think this may be useful.

**Comment by seanupton** [comment]
## A few presumptions:
* Make issue PDFs from page (derivative) PDFs, not from primary file / image of page.
* Require Rails 5.1+ (ActiveJob retry support)
* Ghostscript just merges PDFs — means no need for other (new) image transformations.

## We already have PDFs of pages
* Either we have PDFs from ingest, or from NewspaperWorks derivative creation, or
* if a PDF is not there, there is an expectation that a job is working to create one.

## Details / deliverables:
1. We don't have to hold any new opinions about encoding the PDFs, we just have to merge what's already included as single-page PDF for page into a multi-page file, in the correct order.
2. We can just use Ghostscript — we don't have to use Imagemagick to convert primary files, which is wasteful if we have already done it, or it we already have a PDF from NDNP ingest.
3. Here, Ghostscript's job is just to merge single-page PDFs into multi-page PDFs, and the command syntax for this is simple: https://www.linux.com/news/putting-together-pdf-files
4. *Caveat:* we need to wait to merge pages until all page PDFs are completely ready.  **This may require dependency on Rails 5.1, if we want to have an ActiveJob that just keeps retrying until such derivatives of child works of issue are completely made/ingested.**
5. Deliverables:
* a service or other component, which given an issue work, gets all pages, in order, and creates a list of derivative paths to pass to Ghostscript command invocation, executing; raises exception `NewspaperWorks::PagesNotReady` early in execution if page PDFs are not ready for use, where "ready for use" is defined as: (a) non-empty PDF file exists for fileset in derivative path"; (b) said PDF file does not have a file descriptor listed by the  UNIX `lsof` command that appears to be opened by imagemagick `convert` binary (which would be writing it).
* an ActiveJob job that calls this service, which has set the following declaration to retry with exponential back-off: `retry_on NewspaperWorks::PagesNotReady wait: :exponentially_longer, attempts: 10`
* Tests for service
* Tests for job
* Readme, documentation adjustments
* Adjust travis config and gemspec dependencies to only support Rails 5.1 for now.

**Comment by ebenenglish** [comment]
Fixed via #181
