### ISSUE TITLE
Refactor edition field to distinct name, number fields

### ISSUE THREAD

**Issue by seanupton** [marriott-library/newspaper_works#160]
_Moved from description of #154, for which this item is no longer in scope._

Having a single field for edition is proving insufficient to maintain both ingest of edition values from NDNP without loss, and also preservation of semantic URLs using edition number.  

Part of this challenge is due to use of `bibo:edition` predicate, which **should be retired in favor of Bibframe 2.0 predicates** for edition statement (`bf:editionStatement`) for name of edition, and edition number (`bf:editionEnumeration`).  These are available via the `RDF::Vocab::BF2` vocabulary.

## Deliverables

To be enumerated here, work in progress.

**Comment by ebenenglish** [comment]
Fixed via #164.
