### ISSUE TITLE
install Chrome on samvera-newspapers-vagrant

### ISSUE THREAD

**Issue by ebenenglish** [marriott-library/newspaper_works#168]
We need to add Chrome to the default Vagrant install, or there will be spec failures when trying to run feature specs that require JS interaction.

Command-line install should be _something_ like:
```
$ wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
$ sudo apt-get -f install
$ sudo apt-get install libxss1 xdg-utils libappindicator3-1
$ sudo dpkg -i google-chrome-stable_current_amd64.deb
```
Some refinement/testing needed, the above steps are approximated from several online tutorials.

(Sorry to be putting this here, the [samvera-newspapers-vagrant](https://github.com/marriott-library/samvera-newspapers-vagrant) repo doesn't have an Issues tab.)

**Comment by brianmcbride** [comment]
Chrome has been added to samvera-newspapers-vagrant. @ebenenglish PR for review https://github.com/marriott-library/samvera-newspapers-vagrant/pull/10

**Comment by ebenenglish** [comment]
Closed via https://github.com/marriott-library/samvera-newspapers-vagrant/pull/10.
