### ISSUE TITLE
Add Rubocop to default CI task

### ISSUE THREAD

**Issue by brianmcbride** [marriott-library/newspaper_works#18]
We need to implement Rubocop testings into the CI testing workflow. The following code needs to be added to the master branch:

In the tasks/newspaperworks_dev.rake file replace existing code at line 23 with 

task ci: ['rubocop', 'engine_cart:generate'] do

**Comment by brianmcbride** [comment]
PR  #19 created to address this issue. Merge planned for a future date.

**Comment by ebenenglish** [comment]
Fixed via #183.
