### ISSUE TITLE
Add Metadata field & Enable geolocations

### ISSUE THREAD

**Issue by brianmcbride** [marriott-library/newspaper_works#2]
**Descriptive Summary**

Due to the uniqueness of newspapers, we need to add a specific metadata field called Place of Publication to the metadata profile. Additionally, we want to enable geonames.org lookup functionality to the metadata field to allow the users of NewspapersWorks to be able to add location data based of geonames.org and also allow this data to be indexed and faceted. 

*  Add Metadata field "Place of Publication" to the Title, Container, Issue, and Article metadata model
*  Set the Place of Publication metadata field to source geolocation information from geonames.org based on user input value from the form.

**Rationale**

It's important to implement geonames.org to help provide location based information and a coordinated way to improve the quality of the metadata which will allow for a better end user experience.

**Expected behavior**

Repository managers/depositors can expect to enter in location information, i.e. into the Place of Publication field in the "Add Works" forms and have a set of options returned from geolocations.org, from which they can select a single option.

The new metadata field should be indexed and searchable by the end user and faceting should be enabled.

**Additional Information**

Hyrax, if enabled, can support geonames.org searching. Enabling the geonames.org searching functionality by uncommenting out config.geonames_username and setting name to 'username'

config/initializers/hyrax.rb
(approx lines 99-101)

    #Location autocomplete uses geonames to search #for named regions
    #Username for connecting to geonames
    config.geonames_username = 'username'

**Comment by seanupton** [comment]
Superseded by #29, closed per Sept. 20 discussion as a result.
