### ISSUE TITLE
Programmatic page, issue ingest

### ISSUE THREAD

**Issue by seanupton** [marriott-library/newspaper_works#20]
## General goal

* Provide 60% of the needed pieces (under the hood) for implementation of #8.
* Ability to programmatically attach a work in Ruby, without upload through browser, to works in Hyrax, specifically:
    * Single source file ingest of (image) file representation for `NewspaperPage` objects.
    * Single source file ingest of (image/document) file representation for `NewspaperIssue` objects.
    * Agnostic to source format (if directly attached to `NewspaperPage`), provided the file type is supported by Hyrax (and hydra-derivatives and/or MiniMagick) out of the box.
    * Ability to run ingest on existing work repeatedly for multiple files (appending each) is assumed, but may be optional scope for initial testing.  _The general assumption is to append a new FileSet with each new file_.
* Have a reasonable degree of re-use for above, such that it could be used:
    * By later code we write to intercept upload in Hyrax (actor, job(s));
    * In a rails console session;
    * In one-off scripts
    * In more complex future ingestion pipelines (e.g. a future REST API, or something that pulls assets from cloud storage, etc).
* Work on and manipulate persisted model objects, but not have this ingest implemented on model classes.

## Deliverables

* Work will be done in [pdfingest](/marriott-library/newspaper_works/tree/pdfingest) branch.
* Create module `NewspaperWorks::Ingest`, see [here](https://github.com/marriott-library/newspaper_works/tree/0ae7a79aa80754eac69fa89ba80a1ba3d0bfc11b/lib/newspaper_works/ingest).
* Create series of adapter classes which act upon a work context.
    * `BaseIngest` class implementing common IO and filename wrangling, and a standard way to provide subclasses file stream and file name.
    * A `NewspaperPageIngest` class providing for the attachment of an image file to a `NewspaperPage` work (and subsequent creation of derivatives).
        * Ensure that default Hyrax behaviors for new works (jobs usually run by actor stack) are eventually run for this attachment.
            * e.g. Create derivatives and thumbnails.
    * A `NewspaperIssueIngest` class providing for:
        * The creation of split page master images from multi-page PDF via MiniMagick (but we need a directory to write this to, TBD).
        * Code to instantiate, attach, and persist new `NewspaperPage` for each of above.
            * We need to pick a reasonable way to create titles for these works?
            * Ensure that default Hyrax behaviors for new works (jobs usually run by actor stack) are eventually run for each page.
* A sample script to create page works from one or more paths.
* If User.current_user is unavailable, use User.batch_user as depositor for work.   Need to determine most sensible place to put this.
    * `Hyrax::AttachFilesToWorkJob` assumes work.depositor is set.
    * We likely want to set depositor if it is not already set when performing an upload, but only if we plan to re-use existing Hyrax code that requires it.
* RSpec shared example tests for `BaseIngest` with coverage of all methods, simulating both accepted and error conditions.
* RSpec tests for `NewspaperPageIngest` verifying everything we can verify on non-async results.
* RSpec tests for `NewspaperPageIngest` verifying everything we can verify on non-async results.

## Tools and dependencies

* Ghostscript
  - Splits pages, renders TIFFs from PDF.
* Poppler >= 0.19
  - Used to introspect PDF image data.
* Imagemagick
  - `identify` executable used in testing.
  - MiniMagick occasionally used.

## Quality assumptions

* All tests, including new pass.
* All rubocop checks pass.
* We may want to force-inline some jobs at a later time, this is out of scope for this ticket.

**Comment by seanupton** [comment]
A few additional notes in the [wiki](https://github.com/marriott-library/newspaper_works/wiki/PDF-Ingest-Notes#coding-ingest-to-work-with-hyrax).

**Comment by ebenenglish** [comment]
Resolved by #30.
