### ISSUE TITLE
Depend on Hyrax 2.3.3

### ISSUE THREAD

**Issue by seanupton** [marriott-library/newspaper_works#22]
Move dependency to Hyrax 2.2.4.

**Comment by brianmcbride** [comment]
Hyrax 2.2.0 Release notes: https://github.com/samvera/hyrax/releases

**Comment by seanupton** [comment]
Updated version referenced for this issue to Hyrax 2.2.4, which was released 2018-09-11.

**Comment by crocken** [comment]
Texas Digital Library x Bridge2Hyku pilot would love to test the rubygem, but would need it to be useable with Hyrax 2.3

**Comment by ebenenglish** [comment]
@crocken We've changed our target on this issue to 2.3.3. Should hopefully have the updated dependency merged by week of November 5-9.

**Comment by ebenenglish** [comment]
Update version referenced for this issue to 2.3.3, which was released 2018-10-02.

**Comment by ebenenglish** [comment]
Closed via #66.
