### ISSUE TITLE
Page objects created via PDF Issue upload should have same permissions as parent

### ISSUE THREAD

**Issue by ebenenglish** [marriott-library/newspaper_works#38]
**User story**

As an admin user
When I create a new NewspaperIssue work via the admin UI
And I upload a PDF as an attachment to that work
The NewspaperPage objects that are created representing the pages of the issue
Should have the same access/edit/visibility permissions as the parent Issue object

**Discussion**

Current permissions discrepancy exists where child Page objects are set to `visibility_ssi:"hidden"` in Solr, even if parent Issue has `visibility_ssi:"open"`.

Both Issue and Page have the same `depositor` info.

**This ticket will be complete when:**

Automatically-created Page objects have same access/edit/visibility permissions as parent Issue.

**Comment by seanupton** [comment]
@ebenenglish to clarify, my read is that the scope of this ought to include not only synced permissions at creation time, but also after updates/changes to the visibility of the issue?  Can you confirm that is the intent?  

My [latest commit](https://github.com/marriott-library/newspaper_works/commit/441850baa06779b38cb5ef82f9253e6e331f7d55) takes care of creation-time permission sync but not yet the update of NewspaperIssue permission sync.  

Effect of leaving it with only create-time sync (copy permissions) is to require getting permissions right on initial upload or ingest.  OTOH, there may be corner cases where certain child pages should have distinct permissions from their parent issue, but I cannot yet contemplate the particulars.

**Comment by ebenenglish** [comment]
I think that the scope of this is only creation-time permission sync.

We can create a backlog issue for non-creation/ingest update/change permissions propagation to child Page objects.

**Comment by ebenenglish** [comment]
Fixed via #127.
