### ISSUE TITLE
create module for scanned image metadata

### ISSUE THREAD

**Issue by ebenenglish** [marriott-library/newspaper_works#4]
**Descriptive Summary**
Object types that represent scanned page images (`NewspaperPage`) have specific metadata properties that should be defined in a separate module.

**Rationale**
Putting these properties in a separate module helps keep the code DRY, ensures consistency between object types, makes downstream modifications easier, and mimics the pattern already in use for `NewspaperCoreMetadata`.

**Expected Outcomes**
1. A new module (`ScannedResourceMetadata`? `NewspaperScanMetadata`?) in which metadata properties shared by scanned media objects are declared.
2. Several properties from the [Metadata Profile](https://docs.google.com/spreadsheets/d/1cTiMHywCiyW_9kBegSeFP4tFMkpm0Fgm0T2eHy50F74/edit?usp=sharing) should be added to the new module (don't necessarily need all properties yet, maybe start with `Text direction` and `Page number`).
2. This module should be included in the model class for NewspaperPage.
3. Some basic tests to make sure the properties can be set/get on the model classes (pattern used for `NewspaperCoreMetadata` specs should be fine).

**Comment by seanupton** [comment]
Done; implemented in newsapp-experiments in previous sprint, closing.
