### ISSUE TITLE
Index page text derivative, if one exists

### ISSUE THREAD

**Issue by seanupton** [marriott-library/newspaper_works#49]
Index text of a `NewspaperPage` to a dynamic Solr index named `full_text_tesi` — if the text is available as a derivative file with a `.txt` extension, read that file and index its contents.

The primary use for this is the indexing of OCR-extracted text, or any text saved for page on any other type of ingest.

### Scope

* Indexing is limited to `NewspaperPage` and any more elaborate indexing of parent `NewspaperIssue` for text is out of the scope at the moment (esp. until we figure out how we want to manage the UX for search re: transitive relationships).

**Comment by ebenenglish** [comment]
Fixed via #50.
