### ISSUE TITLE
Adapter to attach and CRUD for primary, derivative files to work

### ISSUE THREAD

**Issue by seanupton** [marriott-library/newspaper_works#57]
Create an adapter component `NewspaperWorks::Data::AttachFiles` that:

1. Is constructed with a single parameter `NewspaperPage` work context;
2. Has an `.attach` method that takes one or more hash arguments of name, path.
  - On attach, gets or creates file set for work.
  - If hash key is `:master`, then attach master file to work.
  - Otherwise, store derivative:
    - hash key should be name for derivative (either 'thumbnail' or file extension)
    - use `Hyrax::DerivativePath` to obtain path for derivatives
    - copy derivative file to appropriate location.
3. _(optional, TBD)_ For completeness, we might want to have a `.remove` function that similarly takes a hash and removes attached file or derivative from a work?

## Usage and intent

* Use for ingest of existing NDNP assets (TIFF master; JP2, PDF, ALTO derivatives)
* Use for ingest of temp files created during ingest from NDNP assets (thumbnail, JSON word coordinate, plain text).

**Comment by ebenenglish** [comment]
Closed via #78.
