### ISSUE TITLE
move code from newsapp-experiments into newspaper_works

### ISSUE THREAD

**Issue by ebenenglish** [marriott-library/newspaper_works#6]
Now that we have a few development cycles under our belt, we need to move the code written for models, metadata, indexing, relationships, etc. out of the `newsapp-experiements` app and into the `newspaper_works` gem.

The end result of this task will be:
1. All code written to date should be moved into the `newspaper_works` gem

2. The README for `newspaper_works` should indicate any customizations in the local app that are needed for the code to work properly (modifications to Hyrax configs, GeoNames username, etc.)

3. `newsapp-experiments` should be a plain vanilla Hyrax app, which includes `newspaper_works` in its Gemfile (e.g. `gem 'newspaper_works', :git => 'https://github.com/marriott-library/newspaper_works'`)

4. A developer should be able to run the specs using the `rake spec` command. The [Hyrax Development Guide](https://github.com/samvera/hyrax/wiki/Hyrax-Development-Guide) offers some clues as to how to set up the gem to allow a test application to be built to run the specs against.

**Comment by seanupton** [comment]
As of 3543d4b466aac6ae98ea1952da530cfeb24276b1, all except #2 above are complete.  All tests run via `rake spec` on master.  I will aim to wrap up initial integration documentation shortly, so we can close this ticket this week.

**Comment by seanupton** [comment]
Closing, with changes to README.md in 299bd1af598df58bfa7b309cf09754147b98891d feeling sufficient to satisfy criteria 2 and 4 above, for now.
