### ISSUE TITLE
add all descriptive metadata fields to metadata modules

### ISSUE THREAD

**Issue by ebenenglish** [marriott-library/newspaper_works#7]
**Descriptive Summary**
The metadata modules that are mixed in to newspaper content models need to be fleshed out with the full list of fields defined in the [Metadata Profile for Newspaper Objects](https://docs.google.com/spreadsheets/d/1cTiMHywCiyW_9kBegSeFP4tFMkpm0Fgm0T2eHy50F74/edit#gid=0).

Modules:
* `NewspaperCoreMetadata` (app/models/concerns/newspaper_works/newspaper_core_metadata.rb)
* `ScannedMediaMetadata` (app/models/concerns/newspaper_works/scanned_media_metadata.rb)

In some cases:
* The metadata field already exists in `Hyrax::BasicMetadata` ("Language," for example). In these cases (marked in the metadata profile doc), we'll use the Hyrax definition for the field, no need to re-declare.
* The metadata profile calls for the use of a controlled vocabulary to define possible values ("Frequency," for example). It may be desirable/necessary to define/copy the vocabulary locally if the list of possible values is small enough. See how Hyrax handles rights statements and licenses for a possible example?
* The field should be added directly to the model, if it is not shared among other content objects ("Subject" in `NewspaperArticle` for example.)

**Expected Behavior**
1. Values for each field can be get/set on an instance of a content model by calling a method matching the field name, e.g.
```ruby
issue = NewspaperIssue.new
issue.edition = "4th ed."
issue.edition
=> "4th ed."
```
2. Values are persisted in Fedora when the object is saved.
```ruby
issue = NewspaperIssue.new
issue.edition = "4th ed."
issue.save
issue.reload
issue.edition
=> "4th ed."
```
(_NOTE: UX of forms for setting/editing metadata values is not in the scope of this ticket, and will be addressed later._)

**This ticket will be complete when:**
1. All fields from the metadata profile have been added to the appropriate module or class
2. Values for fields can be set and are persisted in Fedora on object save
3. Tests for the fields are added to the specs.

**Comment by seanupton** [comment]
Now that I have working RSpec tests ported from newsapp_experiments, we likely want to have some property enumeration fields added to satisfy criterion 3 above, see https://github.com/marriott-library/newspaper_works/blob/master/spec/models/newspaper_title_spec.rb#L17 for example of where this needs to go.

**Comment by ebenenglish** [comment]
I did some review of the metadata work to date, here are a few updates needed (in addition to adding field tests to specs):

**ISSN, LCCN, OCLC fields**
1. Move these into `NewspaperCoreMetadata`
2. Remove from `Title`, `Container`, `Issue`, and `Article` models

**NewspaperTitle**
1. Change URI for `frequency` field to: `http://rdaregistry.info/Elements/u/P60538`

**Newspaper Container**
1. remove `resource_type` field (exists in Hyrax)
2. add Github issue URL to TODO for `reel#`: `https://github.com/samvera-labs/uri_selection_wg/issues/2`

**NewspaperIssue**
1. remove `alternative_title` field (exists in `NewspaperCoreMetadata`)
2. add `extent` field
3. add Github issue URL to TODO for `reel#` (see above)

**NewspaperPage**
1. remove `text_direction` field (exists in `ScannedMediaMetadata`)
2. add Github issue URL to TODO for `reel#` (see above)
3. add `width` field, as defined in `ScannedMediaMetadata`, but comment it out (supposedly exists in `Hyrax::FileSet`, but that remains to be seen)
3. add `height` field, as defined in `ScannedMediaMetadata`, but comment it out (see above)

**NewspaperArticle**
1. remove `creator` field (exists in Hyrax)
2. remove `contributor` field (exists in Hyrax)
3. remove `subject` field (changed profile to use Hyrax field definition)
4. remove duplicate `section` field declaration
5. add Github issue URL to TODO for `reel#` (see above)
6. remove `section` field (exists in `ScannedMediaMetadata`)
7. remove `pagination` field (exists in `ScannedMediaMetadata`)

**ScannedMediaMetadata**
1. remove `identifier` field (exists in Hyrax)
2. remove `height` field (moved to `Page`)
3. remove `width` field (moved to `Page`)

**Comment by ebenenglish** [comment]
In the course of some console testing, I found a couple more issues (sorry for not catching these earlier!):

**NewspaperTitle**
1. remove `publication_date` (exists in `NewspaperCoreMetadata` as `issued`)
2. `edition` is duplicated, remove one declaration, preferably [this one](https://github.com/marriott-library/newspaper_works/blob/master/app/models/newspaper_title.rb#L59-L66)

**NewspaperPage**
1. remove `page_number` (exists in `ScannedMediaMetadata` as `pagination`)
2. remove `section` (exists in `ScannedMediaMetadata`)
