### ISSUE TITLE
Migrate CI (Travis) to Ubuntu Xenial (16.04)

### ISSUE THREAD

**Issue by seanupton** [marriott-library/newspaper_works#76]
See:

https://blog.travis-ci.com/2018-11-08-xenial-release

Also, slightly related: this environment is fully virtualized, not container-based, which means that the `sudo: false` setting is not supported.

**Comment by seanupton** [comment]
https://docs.travis-ci.com/user/reference/xenial/#differences-from-the-trusty-images

**Comment by ebenenglish** [comment]
Closed via #100.
