### ISSUE TITLE
PDF issue ingest: basic functionality

### ISSUE THREAD

**Issue by ebenenglish** [marriott-library/newspaper_works#8]
**Descriptive Summary**
This goal of this ticket is to provide functionality basic ingest of single issue-level objects that have an associated PDF file, including upload, thumbnail creation, full-text extraction, and download.

*Update:* Splitting the PDF into page-level objects is now in scope of this issue, though it was not before.

**Expected behavior**
As an administrative user, 
I should be able to create a new issue object,
add some basic metadata for the issue,
and upload a PDF file representing that issue.

As an end-user,
I should be able to download PDF of issue,
I should be able to download created page images on NewspaperPage works created.

**This ticket will be complete when:**
1. Issue-level upload of a single item results in the creation of the following objects:
   1. `NewspaperIssue`
   2. child `FileSet`
   3. `File` representing combined images (PDF)
   4. `File` representing extracted text (TXT)
2. extracted text is indexed in Solr record for `NewspaperIssue` object
3. User stories above are fully functional

## Dependencies and/or child issues

| Issue no.  | Description |
| ------------- | ------------- |
| ☑ ~~#20~~  | *Programmatic page, issue ingest* |
| ☑ ~~#33~~ | PDF Issue Upload Actor and Job    |
| ☑ ~~#26~~  | Text and coordinate extraction    |
| ☑ ~~#28~~  | NewspaperPage image derivatives    |

**Comment by seanupton** [comment]
Removed from scope:

```
I should be able to discover newspaper issues that match my search term (in metadata or full text),
and I should see a thumbnail in the search results
and if I click on the thumbnail or issue title in the search results,
I should see the show page for the issue,
and I should be able download a copy of the PDF 
```
