### ISSUE TITLE
Handle deferred derivative attachment on after_create_fileset callback

### ISSUE THREAD

**Issue by seanupton** [marriott-library/newspaper_works#82]
Related to #57, and interdependent on work for #70, and related to calling semantics described in this [gist](https://gist.github.com/seanupton/6983fc74e002ea8b3160f6687b8633e3)...

## It should be possible to:

1. Assign derivatives to a `NewspaperWorks::Data::WorkDerivatives` adapter with no fileset created yet, if and only if WorkDerivatives is accessed in the context of an operation on `NewspaperWorks::Data::WorkFiles`, for example:
```ruby
bare_work = NewspaperPage.new
bare_work.title = ['test']
bare_work.save!
attachment = NewspaperWorks::Data::WorkFiles.of(work)  # adapt a work with no fileset yet
attachment.assign('/path/to/primary.tiff')
attachment.derivatives.assign('/path/to/related.jp2')
attachment.derivatives.assign('/path/to/ocr.txt')
# the above needs to avoid exception, and somehow persist a log of relationships
# between primary, secondary files when no fileset yet exists to formalize such
# relationship.  Likewise, there needs to be a way to ensure that committing this
# set of intended file assignments eventually has all derivative files attached):
attachment.commit!
```
2. As described in above, example ensure those assignments are executed: **when both primary and derivative files are assigned for attachment, and `NewspaperWorks::Data::WorkFiles.commit!` is called, a callback should handle creating the derivatives as soon as the fileset actually exists to be a bond between the primary (stored in Fedora) and derivative (stored in filesystem keyed on fileset id) files.

## Implementation

* Should use overlapping set of ActiveRecord model(s) and RDBMS table(s) used to log derivative attachment as used in implementation to address #70.
* Should inject a callback override into application via install generator, which should call a method ensuring all of:
1. Mimick OOTB Hyrax `:after_create_fileset` handler block (invoke a logging job).
2. Attach derivatives based on fileset id,since on this callback, we have a viable fileset.
  - The fileset during this callback has an `import_url` property, which we must leverage to reconstruct the relationship between primary and derivative attachments, since the code called by such callback must reconstruct a WorkDerivatives adapter out of its original (e.g. calling `attachment.derivatives.assign`) context.
3. Ensure that the log data in DerivativeAttachment table (re: #70) is updated with a non-nil fileset_id.

## Notes:

* Hyrax unfortunately has single-subscriber callback registry, which is less "pluggable" and more just "overridable" — the effect of this may cause some issues for application developers with multiple needs to handle any events (esp. on ingest).  This should be noted in README.
* Because the implementation re: #57 uses `Hyrax::Actors::CreateWithRemoteFilesActor` the actual fileset creation happens synchronously, even though file attach is a queued job.  This makes things easier to work with, though it is different than how Hyrax handles mere uploads.  It seems that most bulk ingest processes written by Hyrax users (AFAICT) use CreateWithRemoteFilesActor as a means to use the default actor stack (and avoid mimicking badly what it does), not CreateWithFilesActor+AttachFilesToWorkJob (which seem restricted to upload use).
  - There may be a future opportunity to refactor `NewspaperWorks::Ingest::BaseIngest` using this arrangement, which may present an alternative solution to #38.

**Comment by ebenenglish** [comment]
Closed via #83
